name: Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit hash to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON }}
      IMAGE_TAG: ${{ github.event.inputs.commit }}
    steps:
      - name: Checkout repository at specific commit hash
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}
      - run: ./scripts/deploy